### ISSUE TITLE
 ENOENT: no such file or directory, open 'C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\tmp\config.yml'

### ISSUE THREAD

**Issue by ksambhi** [ksambhi/jakhu#29]
Hi,
I have found an issue which causes the config to be unable to be opened
Here is the output:

```
$ bin/boss server
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\tmp\config.yml'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.getdata (C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\node_modules\boss-config\app.js:7:26)
    at Object.<anonymous> (C:\Users\Kishan Sambhi\Documents\Projects\boss\boss\boot\libs\certs.js:6:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

Thanks in advanced!

**Comment by ksambhi** [comment]
Hi,
We have found the cause: the config is being loaded before it has been generated.
Thank you for telling us

**Comment by ksambhi** [comment]
Thank you for submitting this issue!
It has now been resolved

**Comment by ksambhi** [comment]
Oh no! Needs to be fixed in tests

**Comment by ksambhi** [comment]
It has now been fixed
