### ISSUE TITLE
Need to change the way config is loaded

### ISSUE THREAD

**Issue by ksambhi** [ksambhi/jakhu#30]
I've found a bug which affects first-time start-up. When you test, or run boss,js through app.js's start() function, you may find you receive the following:

```
Error: ENOENT: no such file or directory, open 'tmp/config.yml'
     at Error (native)
     at Object.fs.openSync (fs.js:549:18)
     at /home/travis/build/Gum-Joe/boss.js/boot/libs/configure.js:79:8
     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
 #  Below this is any test exceptions
```

This is due to the fact that boss loads the config by merging all the YAML config files in ./config into one file, called config.yml, into ./tmp. Unfortunately, this file is not created when you first start boss up and the file is parsed before it is created. This throws an error.

We solved this problem, temporalily, by `execSync()`ing a file to load the config and create config.yml` during boot. Since this is not done in app.js, it crashes the tests

We will soon fix this!

**Comment by ksambhi** [comment]
Fixed in commit 08ecffc
